# Generated by Django 4.2.14 on 2024-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='myapps/zipfiles', verbose_name='zip_file')),
            ],
            options={
                'verbose_name': 'MyApp',
                'verbose_name_plural': 'MyApps',
            },
        ),
    ]
